// Code generated by mockery v1.0.0. DO NOT EDIT.

// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT License was not distributed with this
// file, you can obtain one at https://opensource.org/licenses/MIT.
//
// Copyright (c) DUSK NETWORK. All rights reserved.

package mocks

import (
	wire "github.com/dusk-network/dusk-blockchain/pkg/p2p/wire"
	mock "github.com/stretchr/testify/mock"
)

// EventProcessor is an autogenerated mock type for the EventProcessor type
type EventProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: _a0
func (_m *EventProcessor) Process(_a0 wire.Event) {
	_m.Called(_a0)
}
