// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import user "github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user"

// Reducers is an autogenerated mock type for the Reducers type
type Reducers struct {
	mock.Mock
}

// IsMember provides a mock function with given fields: _a0, _a1, _a2
func (_m *Reducers) IsMember(_a0 []byte, _a1 uint64, _a2 uint8) bool {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte, uint64, uint8) bool); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Quorum provides a mock function with given fields:
func (_m *Reducers) Quorum() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// UpdateProvisioners provides a mock function with given fields: _a0
func (_m *Reducers) UpdateProvisioners(_a0 user.Stakers) {
	_m.Called(_a0)
}
