# general node configs
[general]
network = "test"
# walletonly will prevent the node from starting consensus components when the wallet is loaded
walletonly = false

[custom]
key = "value"

[[profile]]
name = "heap"

[[profile]]
name = "cpu"
