package msg

const InitializationTopic = "initialization"
const RoundUpdateTopic = "roundupdate"
const BlockSelectionTopic = "blockSelection"
const SetSelectionTopic = "setSelection"
const ReductionResultTopic = "reductionresult"
const NewProvisionerTopic = "newprovisioner"
const ProvisionerAddedTopic = "provisioneradded"
const SigSetSelectionTopic = "sigSetSelectionTopic"
const SigSetAgreementTopic = "signatureSetAgreement"
const BlockAgreementTopic = "blockAgreement"
const PhaseUpdateTopic = "phaseUpdate"
const OutgoingReductionTopic = "outgoingreduction"
const OutgoingAgreementTopic = "outgoingagreement"
const QuitTopic = "quit"
const BidListTopic = "bidlistTopic"
