package msg

const InitializationTopic = "initialization"
const RoundUpdateTopic = "roundupdate"
const BlockGenerationTopic = "blockgeneration"
const BlockSelectionTopic = "blockSelection"
const ReductionResultTopic = "reductionresult"
const NewProvisionerTopic = "newprovisioner"
const ProvisionerAddedTopic = "provisioneradded"
const SigSetGenerationTopic = "sigsetgeneration"
const SigSetSelectionTopic = "sigSetSelectionTopic"
const SigSetAgreementTopic = "signatureSetAgreement"
const BestScoreTopic = "bestScoreTopic"
const BlockAgreementTopic = "blockAgreement"
const PhaseUpdateTopic = "phaseUpdate"
const OutgoingBlockReductionTopic = "outgoing_block_reduction"
const OutgoingBlockAgreementTopic = "outgoing_block_agreement"
const OutgoingSigSetReductionTopic = "outgoin_gsigset_reduction"
const OutgoingSigSetAgreementTopic = "outgoin_gsigset_agreement"
const OutgoingSigSetTopic = "outgoing_sigset"
const QuitTopic = "quit"
const BidListTopic = "bidlistTopic"

// TODO: demo topics, review/remove
const StakeTopic = "stake"
const BidTopic = "bid"
